apiVersion: apps/v1
kind: Deployment
metadata:
  name: {NAME}-{VERSION}
  labels:
    run: {NAME}-{VERSION}
    branch: {BRANCH}
spec:
  selector:
    matchLabels:
      run: {NAME}-{VERSION}
  replicas: 3
  template:
    metadata:
      labels:
        run: {NAME}-{VERSION}
        branch: {BRANCH}
    spec:
      containers:
        - name: {NAME}-{VERSION}
          image: registry.youthclubstage.de:5000/{NAME}:{VERSION}
          ports:
             - containerPort: {PORT}
          env:
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: mail.host
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: mail.password
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: mail.username
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: mail.port
            - name: MAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: mail.address
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: google.secret
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: db.url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: db.password
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: admin.user
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yc-auth-service-secret
                  key: admin.password