apiVersion: apps/v1
kind: Deployment
metadata:
  name: {NAME}-{VERSION}
  labels:
    run: {NAME}-{VERSION}
    branch: {BRANCH}
spec:
  selector:
    matchLabels:
      run: {NAME}-{VERSION}
  replicas: 3
  template:
    metadata:
      labels:
        run: {NAME}-{VERSION}
        branch: {BRANCH}
    spec:
      containers:
        - name: {NAME}-{VERSION}
          image: registry.youthclubstage.de:5000/{NAME}:{VERSION}
          ports:
             - containerPort: {PORT}
#        - env:
#            - name: ADMIN_USER
#              valueFrom:
#                secretKeyRef:
#                  name: auth-service-cred
#                  key: admin.user
#            - name: ADMIN_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: auth-service-cred
#                  key: admin.password