apiVersion: apps/v1
kind: Deployment
metadata:
  name: {NAME}-{VERSION}
  labels:
    run: {NAME}-{VERSION}
    branch: {BRANCH}
spec:
  selector:
    matchLabels:
      run: {NAME}-{VERSION}
  replicas: 3
  template:
    metadata:
      labels:
        run: {NAME}-{VERSION}
        branch: {BRANCH}
    spec:
      containers:
        - name: {NAME}-{VERSION}
          image: registry.youthclubstage.de:5000/{NAME}:{VERSION}
          ports:
             - containerPort: {PORT}
          env:
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: host
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: username
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: port
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: secret