server:
  port: 8080
  servlet:
      context-path=/auth:
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://auth-server-postgres:5432/postgresdb
    username: postgresadmin
    password: admin123
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /resources/templates
      suffix: .jsp
management:
  endpoint:
    health:
      show-details: always
cors:
  allowedOrigins: '*'
  allowedHeaders:
    - Authorization
    - Content-Type
  exposedHeaders:
    - Authorization
    - Content-Type
logging:
  level:
    org.springframework.security: DEBUG
init:
  admin: ${ADMIN_USER:demo}
  password: ${ADMIN_PASSWORD:demo}