server:
  port: 8190
  servlet:
      context-path=/auth:
spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      #password: example
      port: 27017
      repositories:
        enabled: true
      #username: root
      database: auth
  mvc:
    view:
      prefix: /resources/templates
      suffix: .jsp
management:
  endpoint:
    health:
      show-details: always
cors:
  allowedOrigins: '*'
  allowedHeaders:
    - Authorization
    - Content-Type
  exposedHeaders:
    - Authorization
    - Content-Type
logging:
  level:
    org.springframework.security: DEBUG
init:
  admin: ${ADMIN_USER:demo}
  password: ${ADMIN_PASSWORD:demo}